#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════
   Phase 57 Item 5 — demo data seeder (generator).
   Reads live demo-account ids + staple food ids via the local
   .temp/apply-sql.mjs helper (keeps credentials out of this file)
   and emits supabase/seed-demo.sql — an idempotent, marker-scoped
   seed for the DEMO identities ONLY (trainer@azfit.demo /
   client@azfit.demo). Never touches a real client.
   Regenerate: node scripts/seed-demo.mjs
   ═══════════════════════════════════════════════════════════════ */

import { writeFileSync } from "fs";
import { execSync } from "child_process";

const sql = (q) => execSync(`node .temp/apply-sql.mjs "" "${q.replace(/"/g, '\\"')}"`, { encoding: "utf8" }).trim();
const rowsOf = (q) => JSON.parse(sql(q));

/* ── resolve live demo identities ── */
const trainer = rowsOf("select id from profiles where email='trainer@azfit.demo';")[0]?.id;
const clientProfile = rowsOf("select id from profiles where email='client@azfit.demo';")[0]?.id;
const clientRow = rowsOf("select id from clients where email='client@azfit.demo';")[0]?.id;
const form = rowsOf("select id from check_in_forms where active=true order by created_at limit 1;")[0]?.id;
if (!trainer || !clientProfile || !clientRow || !form) {
  console.error("Missing demo identity rows:", { trainer, clientProfile, clientRow, form });
  console.error("Run supabase/demo-seed.sql first (creates the demo accounts).");
  process.exit(1);
}

/* ── resolve staple foods by name (seed-staples, Phase 39) ── */
const foodId = (name) =>
  rowsOf(`select id from foods_cache where source='seed-staples' and name='${name}' limit 1;`)[0]?.id;
const FOODS = {
  oats: foodId("Rolled Oats"),
  banana: foodId("Banana"),
  chicken: foodId("Chicken Breast"),
  rice: foodId("White Rice, Cooked"),
  eggs: foodId("Whole Eggs"),
  yogurt: foodId("Greek Yogurt 0%"),
};
const missing = Object.entries(FOODS).filter(([, v]) => !v).map(([k]) => k);
if (missing.length) {
  console.error("Missing staple foods:", missing);
  process.exit(1);
}

const PROGRAM = "AzFIT Demo Program";

const out = `-- ============================================================
-- Phase 57 Item 5 — DEMO DATA SEED (demo accounts ONLY).
-- Generated by scripts/seed-demo.mjs — regenerate, don't hand-edit.
-- Idempotent: marker-scoped deletes first, then inserts.
-- Scoped to: trainer@azfit.demo / client@azfit.demo (Alex Carter DEMO).
-- Apply: node .temp/apply-sql.mjs supabase/seed-demo.sql
-- ============================================================

DO $$
DECLARE
  v_trainer uuid := '${trainer}';
  v_client_profile uuid := '${clientProfile}';
  v_client uuid := '${clientRow}';
  v_form uuid := '${form}';
  v_program uuid;
  w_up uuid; w_low uuid; w_full uuid;
  ex uuid;
  log_id uuid;
BEGIN
  /* ── 0. Marker-scoped cleanup (idempotent re-runs) ── */
  DELETE FROM workout_log_entries WHERE workout_log_id IN (
    SELECT wl.id FROM workout_logs wl JOIN workouts w ON w.id = wl.workout_id
    JOIN programs p ON p.id = w.program_id WHERE p.name = '${PROGRAM}');
  DELETE FROM workout_logs WHERE workout_id IN (
    SELECT w.id FROM workouts w JOIN programs p ON p.id = w.program_id WHERE p.name = '${PROGRAM}');
  DELETE FROM exercises WHERE workout_id IN (
    SELECT w.id FROM workouts w JOIN programs p ON p.id = w.program_id WHERE p.name = '${PROGRAM}');
  DELETE FROM workouts WHERE program_id IN (SELECT id FROM programs WHERE name = '${PROGRAM}');
  DELETE FROM programs WHERE name = '${PROGRAM}';
  DELETE FROM sessions WHERE title LIKE 'Demo Session —%' AND trainer_id = v_trainer;
  DELETE FROM nutrition_logs WHERE user_id = v_client_profile;
  DELETE FROM check_in_submissions WHERE client_id = v_client;

  /* ── 1. Demo program (active, started 10 days ago) ── */
  INSERT INTO programs (trainer_id, client_id, name, description, duration_weeks, frequency_per_week, status, start_date)
  VALUES (v_trainer, v_client, '${PROGRAM}', 'Demo program for the sample client', 8, 3, 'active', CURRENT_DATE - 10)
  RETURNING id INTO v_program;

  INSERT INTO workouts (program_id, name, day_of_week, week_number)
  VALUES (v_program, 'Upper Body — Push', 1, 1) RETURNING id INTO w_up;
  INSERT INTO workouts (program_id, name, day_of_week, week_number)
  VALUES (v_program, 'Lower Body', 3, 1) RETURNING id INTO w_low;
  INSERT INTO workouts (program_id, name, day_of_week, week_number)
  VALUES (v_program, 'Full Body', 5, 1) RETURNING id INTO w_full;

  INSERT INTO exercises (workout_id, name, sets, reps, weight_kg, rest_seconds, order_index, notes) VALUES
    (w_up, 'BB Bench Press', 4, '6-8', 60, 150, 0, '{"tempo":"3-0-1-0"}'),
    (w_up, 'Seated DB Shoulder Press', 3, '8-10', 20, 120, 1, '{"tempo":"2-0-2-0"}'),
    (w_up, 'Cable Triceps Pushdown', 3, '10-12', 25, 90, 2, '{"tempo":"2-0-1-0"}'),
    (w_low, 'BB Back Squat', 4, '6-8', 80, 180, 0, '{"tempo":"3-0-1-0"}'),
    (w_low, 'Romanian Deadlift', 3, '8-10', 70, 150, 1, '{"tempo":"3-1-1-0"}'),
    (w_low, 'Walking Lunge', 3, '10 each', 16, 90, 2, '{"tempo":"2-0-1-0"}'),
    (w_full, 'Deadlift', 4, '5', 100, 180, 0, '{"tempo":"2-0-1-0"}'),
    (w_full, 'Pull-Up', 3, '6-8', NULL, 120, 1, '{"tempo":"2-0-2-0"}'),
    (w_full, 'Plank', 3, '45s', NULL, 60, 2, '{"tempo":"hold"}');

  /* ── 2. Completed workout logs (+ entries) over the past 2 weeks ── */
  -- helper shape: one log per past training day, entries per exercise
  -- day -12 (Upper)
  INSERT INTO workout_logs (client_id, workout_id, completed_at, duration_minutes)
  VALUES (v_client, w_up, now() - interval '12 days', 55)
  RETURNING id INTO log_id;
  INSERT INTO workout_log_entries (workout_log_id, client_id, exercise_id, exercise_name, sets_completed, total_sets, reps_per_set, weight_per_set, rpe_per_set)
  SELECT log_id, v_client, e.id, e.name, e.sets, e.sets,
         ARRAY[8,8,7,7], ARRAY[60,60,60,57.5], ARRAY[7,8,8,8.5]
  FROM exercises e WHERE e.workout_id = w_up;

  -- day -9 (Lower)
  INSERT INTO workout_logs (client_id, workout_id, completed_at, duration_minutes)
  VALUES (v_client, w_low, now() - interval '9 days', 60)
  RETURNING id INTO log_id;
  INSERT INTO workout_log_entries (workout_log_id, client_id, exercise_id, exercise_name, sets_completed, total_sets, reps_per_set, weight_per_set, rpe_per_set)
  SELECT log_id, v_client, e.id, e.name, e.sets, e.sets,
         ARRAY[8,8,8,7], ARRAY[80,80,82.5,82.5], ARRAY[7,7.5,8,8.5]
  FROM exercises e WHERE e.workout_id = w_low;

  -- day -6 (Full)
  INSERT INTO workout_logs (client_id, workout_id, completed_at, duration_minutes)
  VALUES (v_client, w_full, now() - interval '6 days', 50)
  RETURNING id INTO log_id;
  INSERT INTO workout_log_entries (workout_log_id, client_id, exercise_id, exercise_name, sets_completed, total_sets, reps_per_set, weight_per_set, rpe_per_set)
  SELECT log_id, v_client, e.id, e.name, e.sets, e.sets,
         ARRAY[5,5,5,5], ARRAY[100,100,102.5,102.5], ARRAY[7,7.5,8,8]
  FROM exercises e WHERE e.workout_id = w_full;

  -- day -2 (Upper again)
  INSERT INTO workout_logs (client_id, workout_id, completed_at, duration_minutes)
  VALUES (v_client, w_up, now() - interval '2 days', 58)
  RETURNING id INTO log_id;
  INSERT INTO workout_log_entries (workout_log_id, client_id, exercise_id, exercise_name, sets_completed, total_sets, reps_per_set, weight_per_set, rpe_per_set)
  SELECT log_id, v_client, e.id, e.name, e.sets, e.sets,
         ARRAY[8,8,8,8], ARRAY[60,60,62.5,62.5], ARRAY[7,7.5,8,8.5]
  FROM exercises e WHERE e.workout_id = w_up;

  /* ── 3. Scheduled week (this Mon completed, Wed + Fri upcoming) ── */
  INSERT INTO sessions (trainer_id, client_id, title, type, status, starts_at, ends_at, location) VALUES
    (v_trainer, v_client_profile, 'Demo Session — Upper Body', '1-on-1', 'completed',
     date_trunc('week', CURRENT_DATE) + interval '9 hours', date_trunc('week', CURRENT_DATE) + interval '10 hours', 'AzFIT Gym'),
    (v_trainer, v_client_profile, 'Demo Session — Lower Body', '1-on-1', 'scheduled',
     date_trunc('week', CURRENT_DATE) + interval '2 days 9 hours', date_trunc('week', CURRENT_DATE) + interval '2 days 10 hours', 'AzFIT Gym'),
    (v_trainer, v_client_profile, 'Demo Session — Full Body', '1-on-1', 'scheduled',
     date_trunc('week', CURRENT_DATE) + interval '4 days 9 hours', date_trunc('week', CURRENT_DATE) + interval '4 days 10 hours', 'AzFIT Gym');

  /* ── 4. Nutrition logs — 3 recent days, staple foods ── */
  INSERT INTO nutrition_logs (user_id, logged_date, meal_type, food_id, quantity_g) VALUES
    (v_client_profile, CURRENT_DATE - 2, 'breakfast', '${FOODS.oats}', 80),
    (v_client_profile, CURRENT_DATE - 2, 'breakfast', '${FOODS.banana}', 120),
    (v_client_profile, CURRENT_DATE - 2, 'lunch', '${FOODS.chicken}', 180),
    (v_client_profile, CURRENT_DATE - 2, 'lunch', '${FOODS.rice}', 250),
    (v_client_profile, CURRENT_DATE - 1, 'breakfast', '${FOODS.eggs}', 150),
    (v_client_profile, CURRENT_DATE - 1, 'lunch', '${FOODS.chicken}', 170),
    (v_client_profile, CURRENT_DATE - 1, 'lunch', '${FOODS.rice}', 220),
    (v_client_profile, CURRENT_DATE - 1, 'dinner', '${FOODS.yogurt}', 200),
    (v_client_profile, CURRENT_DATE, 'breakfast', '${FOODS.oats}', 85),
    (v_client_profile, CURRENT_DATE, 'breakfast', '${FOODS.yogurt}', 150);

  /* ── 5. One check-in submission (this week) ── */
  INSERT INTO check_in_submissions (form_id, client_id, answers, submitted_at)
  VALUES (v_form, v_client,
          '{"weight_kg": 79.2, "energy": 4, "sleep": 4, "stress": 2, "notes": "Feeling strong, knees fine."}'::jsonb,
          now() - interval '1 day');

  RAISE NOTICE 'Demo seed applied: program %, 4 logs, 3 sessions, 10 nutrition logs, 1 check-in', v_program;
END $$;
`;

writeFileSync("supabase/seed-demo.sql", out);
console.log(`Wrote supabase/seed-demo.sql (trainer ${trainer.slice(0, 8)}…, client row ${clientRow.slice(0, 8)}…)`);
